// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV0tmalq57q2wb1JAQ8S9eZ5rVkkVojUA',
    appId: '1:1041153038304:web:22f432936bfbdc5cc07d85',
    messagingSenderId: '1041153038304',
    projectId: 'purrlog-53e0e',
    authDomain: 'purrlog-53e0e.firebaseapp.com',
    storageBucket: 'purrlog-53e0e.firebasestorage.app',
    measurementId: 'G-TQ2F2KN6ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBImP6HRSRJ4MKIKDe_mtxTTMAm6sqnT5Q',
    appId: '1:1041153038304:android:20ebae1451cc13f0c07d85',
    messagingSenderId: '1041153038304',
    projectId: 'purrlog-53e0e',
    storageBucket: 'purrlog-53e0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4v7M8XW7aAXC2PgG516wXRVsz-VaLHso',
    appId: '1:1041153038304:ios:1874ae73f75cacc3c07d85',
    messagingSenderId: '1041153038304',
    projectId: 'purrlog-53e0e',
    storageBucket: 'purrlog-53e0e.firebasestorage.app',
    iosBundleId: 'dev.pawtrack.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4v7M8XW7aAXC2PgG516wXRVsz-VaLHso',
    appId: '1:1041153038304:ios:7185883885cd8c3bc07d85',
    messagingSenderId: '1041153038304',
    projectId: 'purrlog-53e0e',
    storageBucket: 'purrlog-53e0e.firebasestorage.app',
    iosBundleId: 'com.example.petLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAV0tmalq57q2wb1JAQ8S9eZ5rVkkVojUA',
    appId: '1:1041153038304:web:991a86bc6e49a540c07d85',
    messagingSenderId: '1041153038304',
    projectId: 'purrlog-53e0e',
    authDomain: 'purrlog-53e0e.firebaseapp.com',
    storageBucket: 'purrlog-53e0e.firebasestorage.app',
    measurementId: 'G-8JBPXTFZGY',
  );
}
